package com.opositaweb.repository.enums;

public enum Theme {

	DERECHOS_HUMANOS, IGUALDAD, PREVENCION_RIESGOS, CONSTITUCIONAL, UNION_EUROPEA, INTERNACIONAL, CIVIL, PENAL,
	PROCESAL_PENAL, ADMINISTRATIVO, PROTECCION_DATOS, EXTRANJERIA, SEGURIDAD_PUBLICA, MINISTERIO, FUERZAS_SEGURIDAD,
	SOCIO_CULTURAL, TECNICO_CIENTIFICAS, TOPOGRAFIA, DEONTOLOGIA, PENAL_MENORES, VIOLENCIA_GENERO, ARMAS_EXPLOSIVOS,
	FISCAL, INGLES, ESPANOL

}
